version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env
    ports:
    - ${PORT}:${PORT}
    volumes:
      - ./logs:/app/log
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
  redis:
    image: redis:latest